name: fanalytics
description: "Fanalytics is a Flutter plugin for tracking events and user data."
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  dart_ipify: ^1.1.1
  device_info_plus: ^11.2.1
  equatable: ^2.0.7
  firebase_analytics: ^11.4.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
