name: fanalytics
description: "Fanalytics is a Flutter plugin for tracking events and user data."
version: 0.0.3

environment:
  sdk: ^3.5.4
  flutter: '>=3.32.0'

dependencies:
  android_id: ^0.4.0
  dart_ipify: ^1.1.1
  device_info_plus: ^11.5.0
  equatable: ^2.0.7
  firebase_analytics: ^12.0.0
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
